version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_DATABASE=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - app-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"  # Native protocol
      - "8123:8123"  # HTTP interface
      - "8443:8443"  # HTTPS interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  init-sample-data:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_DATABASE=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    command: >
      sh -c "echo 'Waiting for ClickHouse to be ready...';
             while ! wget -q --spider http://clickhouse:8123/ping; do
               sleep 1;
             done;
             echo 'ClickHouse is ready!';
             python init_clickhouse.py"
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  clickhouse_data: 